apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: hmac-auth
  namespace: apps-configuration
spec:
  applyToRoutes:
    - route:
        labels:
          route: main-route
  config:
    glooAuth:
      configs:
        - hmacAuth:
            secretRefs:
              secretRefs:
                - name: hmac-digest
                  namespace: apps-configuration
            parametersInHeaders: {}
    server:
      name: ext-auth-server