apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: gateway
  namespace: apps-configuration
spec:
  workloads:
    - selector:
        labels:
          istio: ingressgateway
        cluster: $CLUSTER_NAME
  listeners:
    - port:
        number: 80
      http: {}