apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: parent-rt
  namespace: apps-configuration
spec:
  virtualGateways:
    - name: gateway
      namespace: apps-configuration
      cluster: $CLUSTER_NAME
  hosts:
    - '*'
  http:
    - delegate:
        routeTables:
          - labels:
              rt: child
        sortMethod: ROUTE_SPECIFICITY