apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: RateLimitClientConfig
metadata:
  name: rl-client-config
  namespace: apps-configuration
spec:
  raw:
    rateLimits:
      - actions:
          - genericKey:
              descriptorValue: counter
        limit:
          dynamicMetadata:
            metadataKey:
              key: envoy.filters.http.ext_authz
              path:
                - key: opa_auth
                - key: rateLimit