apiVersion: v1
kind: Namespace
metadata:
  name: jwt-server
---
apiVersion: v1
kind: Service
metadata:
  name: mock-jwt-service
  namespace: jwt-server
spec:
  selector:
    app: mock-jwt
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-jwt
  namespace: jwt-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-jwt
  template:
    metadata:
      labels:
        app: mock-jwt
    spec:
      containers:
        - name: mock-jwt-container
          image: ghcr.io/stackitcloud/fake-jwt-server:v0.1.1
          args:
            - --port=8008
            - --issuer=jwt-mock-server
            - --audience=gloo
            - --subject=gloo
            - --expires-in-minutes=60
            - --email=test@example.com
          ports:
            - containerPort: 8008