apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: jwks-upstream
  namespace: apps
spec:
  ## no tunnel created here
  static:
    hosts:
      - addr: mock-jwt-service.jwt-server.svc
        port: 8008